package main

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Test Example", func() {
	It("should test example values", func() {
		Expect(Well([]string{"good", "bad", "good", "good", "bad", "good", "bad", "bad", "good", "bad", "bad"})).To(Equal("I smell a series!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "good", "good", "bad", "bad", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "good", "bad", "bad", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad", "bad", "bad", "good", "bad", "bad", "good", "bad", "bad", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "good", "bad", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad", "bad"})).To(Equal("Fail!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "bad"})).To(Equal("Fail!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "good", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad"})).To(Equal("Fail!"))
		Expect(Well([]string{"bad", "bad", "bad", "good", "bad", "good", "good", "bad", "bad", "bad", "bad", "good", "good"})).To(Equal("I smell a series!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "good", "bad", "bad", "bad", "bad", "good"})).To(Equal("Publish!"))
		Expect(Well([]string{"good", "bad", "bad", "bad", "bad", "bad", "bad", "good", "bad", "bad", "good", "bad"})).To(Equal("I smell a series!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "bad", "good", "bad", "good", "good", "good", "bad", "bad", "good"})).To(Equal("I smell a series!"))
		Expect(Well([]string{"bad", "good", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad", "bad", "bad", "good", "bad", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"good", "bad", "bad", "bad", "bad", "good", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"good"})).To(Equal("Publish!"))
		Expect(Well([]string{"good", "good"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad", "bad", "bad", "good", "bad", "bad", "bad", "good", "bad", "bad", "bad", "bad", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"good", "bad", "good", "good", "bad", "bad", "bad"})).To(Equal("I smell a series!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "bad"})).To(Equal("Fail!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "good", "bad", "bad", "bad", "good"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad", "good", "bad", "bad", "good", "bad", "good", "bad", "bad", "bad", "bad", "bad", "bad", "bad"})).To(Equal("I smell a series!"))
		Expect(Well([]string{"bad", "good"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad", "good", "bad", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"good", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "good"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad"})).To(Equal("Fail!"))
		Expect(Well([]string{"bad", "bad", "good", "bad", "bad", "good", "bad", "bad", "bad", "bad", "bad", "good", "good", "bad", "good", "bad"})).To(Equal("I smell a series!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "bad", "bad", "bad", "bad"})).To(Equal("Fail!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "good", "bad", "bad", "bad"})).To(Equal("Publish!"))
		Expect(Well([]string{"bad", "bad", "good", "bad", "bad", "good", "bad", "good", "bad", "bad", "bad"})).To(Equal("I smell a series!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "bad"})).To(Equal("Fail!"))
		Expect(Well([]string{"good", "bad", "bad", "bad", "bad", "bad", "good", "good", "bad", "bad", "bad", "bad", "good", "bad", "bad"})).To(Equal("I smell a series!"))
		Expect(Well([]string{"bad", "bad", "bad", "bad", "bad", "good", "bad", "bad"})).To(Equal("Publish!"))
	})
})
